# EN или RU
# EN or RU
locale: ru

# Телепортировать игрока на спавн при первом входе?
# Teleport the player to the spawn point upon first login?
teleportOnFirstJoin: true

spawn:
  cooldownSeconds: 10     # КД на /spawn
  warmupSeconds: 3        # Задержка перед ТП
  cancelOnMove: true      # Отменять, если игрок двинулся

  antiSpam:
    enabled: true
    windowSeconds: 5        # окно для подсчёта спама
    maxCommands: 5          # макс. команд за окно

database:
  host: localhost
  port: 3306
  name: ru_craft
  user: admin
  password: admin