name: SpawnPlugin
main: ru.craft.plugin.SpawnPlugin
version: 2.1.4
api-version: 1.20
author: Kalimulin.D.A

commands:
  spawn:
    description: Телепортация на спавн
    usage: /spawn
    permission: simple.spawn

  setspawn:
    description: Задать точку спавна
    usage: /setspawn
    permission: simple.setspawn

  sethome:
    description: Установить точку дома
    usage: /sethome

  home:
    description: Телепортация домой
    usage: /home

  delhome:
    description: Удаление точки дома
    usage: /delhome

  back:
    description: Вернуться к последнему месту смерти
    usage: /back
    permission: simple.back

permissions:
  simple.spawn:
    default: true
  simple.setspawn:
    default: op
  simple.back:
    default: true
